### ISSUE TITLE
'uncategorized' 2nd SimpleAnalytics Module  in Admin > Modules

### ISSUE THREAD

**Issue by ghost** [Lombiq/Orchard-Simple-Analytics#1]
thanks for your time
after deleting the 'old' simpleanalytics and loading the new simpleAnalytics  ( github 1.10.1) I find in the admin < modules two (2) of these modules! see attached .png!

I have no idea whether this creates later on any issues?

How do I get rid of the 'uncategorized
![lomanalytics](https://user-images.githubusercontent.com/6625322/28245448-1e64f776-6a07-11e7-9bd4-1fa6681603f2.PNG)
' one?
PS: I only have one (1) Lombiq.SimpleAnalytics folder in my Module folder! BUT I can enable also the uncategorized one!?

**Comment by Piedone** [comment]
The one with the Analytics category is the real one...

This can typically happen if you have the module in multiple instances in the Modules folder and thus there are two Module.txt files corresponding to it. Are you sure this is not the case? Isn't there another folder, even if not named Lombiq.SimpleAnalytics, that contains a Module.txt with the category not set?

**Comment by ghost** [comment]
Hi, you were right, sorry!
My analytics module I named 'LombiqAnalytics'. After I changed the name to 'Lombiq.SimpleAnalytics' ALL
was ok!
Thanks for your time, ed

**Comment by Piedone** [comment]
Great then!
