### ISSUE TITLE
where do/should I set the analytics script?

### ISSUE THREAD

**Issue by ghost** [Lombiq/Orchard-Simple-Analytics#2]
Hi, this question is just for clarification / education
thanks for your time.
 
I have 3 Sites where I use the Lombiq.Simple Analytics. On one (1) Site I see in Admin > Settings the
box to set the Analytics Settings script. On the other two Sites I do NOT have that box.

On the other hand I place the 'script' on ALL Sites in the 'Document.cshtml' file. On ALL Sites 
I receive the Analytics report!

I vaguely recall that Lombiq said once to set it in the 'Document.cshtml'!?

But then for curiosity: 
- why do I NOT see the box in 'settings' on all Sites?
- setting it in 'Doc...' AND in the settings box - does that make sense?
- Do I still need the 'Lombiq.SimpleAnalytics' module when I set it in 'Doc....?!

thanks for your time and clarification, ed

**Comment by Piedone** [comment]
This module is so you can set an analytics script without modifying any source code - this is useful in cases like DotNest where we wanted users to give an easy way of settings such scripts.

If you do can modify the source than that's a more efficient way of doing the same thing, so it's either Document.cshtml or this module, you don't need both.

As for why you don't see the admin settings on two of your sites, I'm not sure. Is the module enabled? Is it under a folder named exactly Lombiq.SimpleAnalytics?

**Comment by ghost** [comment]
Then I will go to use the 'doc...' only!
As far as the box not showing in two of my Sites: I double checked the 'Lombiq.SimpleAnalytics' names - to me all is correct!
Thanks again for your time, ed

**Comment by Piedone** [comment]
Strange, anyway, great then.
